// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1788781763);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1788781763);
user_pref("app.update.lastUpdateTime.glean-addons-daily", 1788781763);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1788781763);
user_pref("app.update.lastUpdateTime.region-update-timer", 1788781763);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1788781763);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1788781763);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1788781763);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "ce522b31-6b91-4da0-aeb8-e8510945cf29");
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1788781735);
user_pref("browser.crashReports.cleanupCheck.lastDate", "2026-09-07T11:54:26.175Z");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1788781733);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 177);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ace2b4e1-bcdf-415b-9807-b64972c10e5d}");
user_pref("browser.newtabpage.activity-stream.newtabWallpapers.user.enabled.migrated", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.preonboarding.splashShown", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.google5.lastupdatetime", "1788781789083");
user_pref("browser.safebrowsing.provider.google5.nextupdatetime", "1788868189083");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1788781735411");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1788803335411");
user_pref("browser.search.totalSearches", 5);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1788781735");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20260825051950");
user_pref("browser.startup.homepage_override.mstone", "154.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1788781736);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"reset-pbm-toolbar-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\",\"ai-window-toggle\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"reset-pbm-toolbar-button\",\"ai-window-toggle\",\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"PersonalToolbar\"],\"currentVersion\":25,\"newElementCount\":2}");
user_pref("browser.urlbar.lastUrlbarSearchSeconds", 1788782113);
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.placeholderName.private", "Google");
user_pref("browser.urlbar.quickactions.timesShownOnboardingLabel", 1);
user_pref("browser.urlbar.quicksuggest.migrationVersion", 7);
user_pref("captchadetection.lastSubmission", 1788781);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "55d8897c-5bad-4f39-b256-17ce3589d806");
user_pref("datareporting.dau.cachedUsageProfileID", "06b01812-ac02-4830-acd1-261b69ee8fa5");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1788781735504");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "154.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.cache.lastUpdate", 1788781763);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-fr@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20260825051950");
user_pref("extensions.lastAppVersion", "154.0.1");
user_pref("extensions.lastPlatformVersion", "154.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"ffdf1c3e-0367-49a7-bf87-48ce0fd57895\",\"ipp-activator@mozilla.com\":\"a058494d-ab68-4ecd-8f78-d76e01a37718\",\"pictureinpicture@mozilla.org\":\"2a91880d-b10d-4823-9531-5bc5ad6908f2\",\"addons-search-detection@mozilla.com\":\"697c350d-5327-46af-885b-b37916e48039\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"26af7839-ac19-444b-a414-701e260b976c\",\"default-theme@mozilla.org\":\"e2893245-939d-45a9-8069-91d5668a4d74\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.hashValue", "f5246bf14d038adf4ce0c4360262ab722bc3de4220f047c3d542b4c564074b4877dc8659e3125c5171c749e7ce93f20cc63777eb5e1539e960670cbc5f30ac85");
user_pref("media.gmp-gmpopenh264.lastDownload", 1788781764);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1788781763);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1788781764);
user_pref("media.gmp-gmpopenh264.version", "2.6.0");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.firstUpdateComplete", true);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 5);
user_pref("nimbus.migrations.init-started", 1);
user_pref("nimbus.profileId", "798eaed5-33fe-4a9e-ae84-620ddf588ea7");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.visibility", "hide-on-close");
user_pref("signon.storage.rust.restoreDone", true);
user_pref("toolkit.profiles.storeID", "28842d44");
user_pref("toolkit.startup.last_success", 1788781728);
user_pref("toolkit.telemetry.cachedClientID", "5a7594cf-450d-41d2-9b76-5961c3dbcf00");
user_pref("toolkit.telemetry.cachedProfileGroupID", "2f8ab606-ccf8-418b-acc2-dd17936e962c");
user_pref("toolkit.telemetry.previousBuildID", "20260825051950");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
